version: "3.5"
networks:
  network:
services:
  server-0:
    container_name: server_0
    environment:
      COUCHDB_PASSWORD: -pbkdf2-847043acc65626c8eb98da6d78682fbc493a1787,f7b1a3e4b624f4f0bbfe87e96841eda0,10
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_USER: admin
      NODENAME: couchdb-0.docker.com
      ERL_FLAGS: "-setcookie brumbrum"
    image: couchdb:2.3.0
    networks:
      network:
        aliases:
          - couchdb-0.docker.com
    ports:
      - "5984:5984"
      - "5986:5986"
    volumes:
      - "volume-0-data:/opt/couchdb/data"
      - "volume-0-etc:/opt/couchdb/etc/local.d"
  server-1:
    container_name: server_1
    environment:
      COUCHDB_PASSWORD: -pbkdf2-847043acc65626c8eb98da6d78682fbc493a1787,f7b1a3e4b624f4f0bbfe87e96841eda0,10
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_USER: admin
      NODENAME: couchdb-1.docker.com
      ERL_FLAGS: "-setcookie brumbrum"
    image: couchdb:2.3.0
    networks:
      network:
        aliases:
          - couchdb-1.docker.com
    ports:
      - "15984:5984"
      - "15986:5986"
    volumes:
      - "volume-1-data:/opt/couchdb/data"
      - "volume-1-etc:/opt/couchdb/etc/local.d"
  server-2:
    container_name: server_2
    environment:
      COUCHDB_PASSWORD: -pbkdf2-847043acc65626c8eb98da6d78682fbc493a1787,f7b1a3e4b624f4f0bbfe87e96841eda0,10
      COUCHDB_SECRET: 0123456789abcdef0123456789abcdef
      COUCHDB_USER: admin
      NODENAME: couchdb-2.docker.com
      ERL_FLAGS: "-setcookie brumbrum"
    image: couchdb:2.3.0
    networks:
      network:
        aliases:
          - couchdb-2.docker.com
    ports:
      - "25984:5984"
      - "25986:5986"
    volumes:
      - "volume-2-data:/opt/couchdb/data"
      - "volume-2-etc:/opt/couchdb/etc/local.d"
volumes:
  volume-0-data:
  volume-1-data:
  volume-2-data:
  volume-0-etc:
  volume-1-etc:
  volume-2-etc:
