- name: Decrease console log level
  become: yes
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '^\$klogConsoleLogLevel'
    line: '$klogConsoleLogLevel 4'
  notify: restart rsyslog

- name: Create custom syslog configs
  become: yes
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
  loop: "{{ rsyslog_configs }}"
  notify: restart rsyslog

- name: Create custom logrotate configs
  include_role:
    name: ansible-logrotate
  when: "logrotate_scripts | length > 0"

- name: Configure logrotate size limit in rsyslog (replacing weekly)
  lineinfile:
    path: /etc/logrotate.d/rsyslog
    regexp: '^	weekly'
    insertbefore: 'missingok'
    line: '	size 750M'
    state: present

- name: Configure logrotate timer (hourly instead of daily)
  lineinfile:
    path: /etc/systemd/system/timers.target.wants/logrotate.timer
    regexp: '^OnCalendar='
    line: 'OnCalendar=hourly'
    insertafter: '^\[Timer\]'
    state: present
