title: configure-java-17-for-formplayer
key: configure-java-17-for-formplayer
date: 2023-01-09
optional_per_env: no
context: |
  This change is to configure Java 17 for Formplayer. 

details: |
  This sets a specific Java version just for formplayer. It should only affect the machine that formplayer is on and it shouldn't imapct other 
  Java processes running on that machine. 

update_steps: |

  1. Update commcare-cloud to the latest version
  2. Add the following setting to the environment's `public.yml` and set its value accordingly:
      ```
      formplayer_java_version: {{ java_17_bin_path }}/java
      ```
  3. Update Formplayer 
      ```
      commcare-cloud <env> ap deploy_formplayer.yml --limit=formplayer
      ```

