- name: Update setuptools
  pip: name=setuptools state=latest

- name: Install ndg-httpsclient so we can download couch
  pip:
    name:
      - ndg-httpsclient

- name: Create couchdb2 dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ couchdb_parent_srcs_dir }}"

- name: Add Couch apt repo (for libmozjs dependency)
  block:
    - apt_key: url=https://couchdb.apache.org/repo/bintray-pubkey.asc state=present
    - apt_repository: repo="deb https://apache.bintray.com/couchdb-deb bionic main" state=present
  when: ansible_distribution_version == '18.04'

- name: Add Erlang apt repo
  block:
    - apt_key: url=https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc state=present
    - apt_repository: repo="deb https://packages.erlang-solutions.com/ubuntu bionic contrib" state=present
  when: ansible_distribution_version == '18.04'

- name: Install Erlang dependencies
  apt:
    name:
      - esl-erlang=1:22.3.4.9-1
      - erlang-mode=1:22.3.4.9-1
    force: yes
  when: couchdb_version is version('3.0.0', '>=')

- name: Install Erlang dependencies 
  apt:
    name:
      - esl-erlang=1:21.3.8.17-1
      - erlang-mode=1:21.3.8.17-1
    force: yes
  when: couchdb_version is version('3.0.0', '<')

