couchdb2_first_host: "{{ groups['couchdb2'][0] if 'couchdb2' in groups else 'NO HOST SHOULD MATCH THIS' }}"

datadog_custom_integrations:
  - name: celery_custom
    url: https://raw.githubusercontent.com/dimagi/datadog-checks/65590924f430ee185eabacd5136a5a52292ae5f7/celery_custom/celery_custom.py
    sha256sum: 1541fb41ae12b6e115eb0fc151d98f2823390ad26643795a64180a4bbb82ad05
    enabled: "{{ app_processes_config.celery_processes.get(inventory_hostname).flower is defined }}"
  - name: couch_custom
    url: https://raw.githubusercontent.com/dimagi/datadog-checks/ce1179c6a5bb621e464770b436e49ab502c0ea33/couchdb_custom/couchdb_custom.py
    sha256sum: a9698756d363dd20b89e2e4e15c5b0c0f6d4acc5ac812e31951fc51acd928d52
    enabled: "{{ inventory_hostname == couchdb2_first_host }}"

monitoring_groups:
  - webworkers
  - hq_webworkers
  - mobile_webworkers
  - proxy
  - elasticsearch
  - postgresql
  - pg_standby
  - pgbouncer
  - shard_dbs
  - main_dbs
  - ucr_dbs
  - formplayer
  - pillowtop
  - celery
  - rabbitmq
  - kafka
  - redis
  - couchdb2
  - couchdb2_proxy
  - django_manage
  - citusdb
