---
- hosts: "{{ control_host }}"
  gather_facts: yes
  remote_user: ubuntu
  tasks:
    - name: (1/2) Clone commcare-cloud
      command: "git clone https://github.com/dimagi/commcare-cloud"

    - name: (2/2) Checkout branch
      command:
        cmd: "git checkout {{ git_branch }}"
        chdir: ~/commcare-cloud
