deploy_env: icds-staging
env_monitoring_id: icds-sandbox
users:
  - dimagi
git_repositories:
  - name: icds
    url: git@github.com:dimagi/commcare-icds.git
    dest: icds
    version: icds-autostaging
    deploy_key: deploy_key.pem
    is_private: true
deploy_keys:
  deploy_key.vault: deploy_key.pem
