code_releases: "{{ www_home }}/releases"
code_source: "{{ code_releases }}/{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}.{{ ansible_date_time.minute }}"
python_name: python{{ python_version }}
virtualenv_source: "{{ code_source }}/python_env-{{ python_version }}"

django_bash_runner: "/bin/bash {{ supervisor_service_files.django_bash_runner.file_path }}"
django_direct_runner: "{{ virtualenv_home }}/bin/python {{ code_home }}/manage.py"

formplayer_java: "{{ formplayer_java_version | default('java') }}"
