---
- hosts: "{{ control_host }}"
  gather_facts: yes
  remote_user: ubuntu
  become: yes
  vars_prompt:
    - name: root_password
      prompt: control machine new root password
      confirm: yes
      private: yes
      encrypt: sha512_crypt
      salt_size: 7

  tasks:
    - name: (1/8) Update Root user's password
      user:
        name: root
        update_password: always
        password: "{{ root_password }}"

    - name: (2/8) Enable root user
      command: "passwd -u root"

    - name: (3/8) Allow root login
      lineinfile:
          path: /etc/ssh/sshd_config
          line: PermitRootLogin yes
          state: present
          backup: yes

    - name: (4/8) Allow password auth
      lineinfile:
          path: /etc/ssh/sshd_config
          line: PasswordAuthentication yes
          state: present
          backup: yes

    - name: (5/8) Reload ssh
      command: "passwd -u root"

    - name: Setup commcare-cloud
      become: yes
      become_user: ubuntu
      block:
      - name: (6/8) Clone commcare-cloud
        command: "git clone https://github.com/dimagi/commcare-cloud"

      - name: (7/8) Checkout branch
        command:
          cmd: "git checkout {{ git_branch }}"
          chdir: ~/commcare-cloud

      - name: (8/8) Copy .pem file
        copy:
          src: "{{ pem_file_path }}"
          dest: "{{ pem_file_path }}"
          mode: 0600
