---
- name: Gather fact 'distribution_version'
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - 'distribution_version'

- name: Create groups based on 'distribution_version'
  ansible.builtin.group_by:
    key: ubuntu_{{ ansible_distribution_version | replace(".", "_") }}

- name: Show 'distribution_version' for non 22.04 hosts
  debug:
    msg: "{{ item }}"
  register: warning_present
  loop: "{% if 'ubuntu_22_04' not in group_names %}{{ warning_host_message }}{% else %}[]{% endif %}"

- name: Show warning if non 22.04 hosts are present
  pause:
    prompt: |-

      The hosts listed above are running a version of Ubuntu which
      we will no longer support after July 1, 2023.

      Failure to upgrade to Ubuntu 22.04 by July 1 may result in
      irreparable harm to the site and its data.

      Please follow the instructions here:
       - https://forum.dimagi.com/t/commcare-cloud-release-notes-2023-03-29/9739
       - https://commcare-cloud.readthedocs.io/en/latest/changelog/0071-upgrade_to_ubuntu_22.04.html

      Press Enter to acknowledge and continue
  when: warning_present.msg is defined
