---

 - name: Add Citus apt key
   apt_key: 
    url: " {{ citus_apt_key_url }}"
    state: present
    
 - name: Add Citus apt repo
   apt_repository: 
    repo: "{{ citus_apt_repo }}"
    state: present
   register: add_citus_repo

 - name: Update package list
   apt: 
    update_cache: yes
   when: add_citus_repo is changed

 - name: Install Citus
   apt: 
    name: "{{citus_binary}}"
    state: present
   notify: Restart postgres

 - name: Install and configure postgresql
   import_role:
     name: postgresql_base
   vars:
     postgresql_version: "{{ citus_postgresql_version }}"
     postgresql_port: "{{ citus_postgresql_port }}"
     postgresql_cluster_name: 'main'
     postgresql_shared_preload_libraries:
       - 'citus'
       - 'pg_stat_statements'
     postgresql_custom_settings: "{{ [\"citus.use_secondary_nodes = 'always'\"] if is_pg_standby and inventory_hostname in groups['citusdb_master']|default([]) else []}}"

 # postgresql_ext bug https://github.com/ansible-collections/community.general/pull/1078
 - name: Get available citus version
   become: yes
   become_user: postgres
   shell: psql postgres -q  -t -c "select version from pg_available_extension_versions where name = 'citus' and version >= '{{ citus_version }}' order by version desc limit 1;"
   register: citus_version_available

 - name: Add Citus Extension
   become: yes
   become_user: postgres
   postgresql_ext:
     name: citus
     db: "{{ item.name }}"
     version: "{{ citus_version_available.stdout | default(citus_version) | trim }}"
   with_items: "{{ postgresql_dbs.all }}"
   when: item.host in groups.citusdb_master

 - name: Set up Citus Worker DBs
   import_tasks: setup_worker.yml
   when: not is_pg_standby and inventory_hostname in groups.citusdb_worker
   tags:
     - configure

 - name: Setup citusdb_master
   import_tasks: setup_cordinator.yml
   when: not is_pg_standby and inventory_hostname in groups.citusdb_master
   tags:
    - configure
