---
- name: Create PostgreSQL databases on Worker
  become_user: "postgres"
  vars:
    ansible_ssh_pipelining: true
  postgresql_db:
    name: "{{ item.name }}"
    state: present
    port: "{{ citus_postgresql_port }}"
    owner: "{{ item.user }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
  when: item.create and item.host in groups.citusdb_master
  with_items: "{{ postgresql_dbs.all }}"
