---
- name: Create PostgreSQL databases on Worker
  become_user: "postgres"
  vars:
    ansible_ssh_pipelining: true
  postgresql_db:
    name: "{{ item.name }}"
    state: present
    port: "{{ citus_postgresql_port }}"
    owner: "{{ item.user }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
  when: item.create and item.host in groups.citusdb_master
  with_items: "{{ postgresql_dbs.all }}"

# postgresql_ext bug https://github.com/ansible-collections/community.general/pull/1078
- name: Get available citus version
  become: yes
  become_user: postgres
  shell: psql postgres -q  -t -c "select version from pg_available_extension_versions where name = 'citus' and version >= '{{ citus_version }}' order by version desc limit 1;"
  register: citus_version_available

- name: Add Citus Extension on Worker Database
  become: yes
  become_user: postgres
  postgresql_ext:
    name: citus
    db: "{{ item.name }}"
    version: "{{ citus_version_available.stdout | default(citus_version) | trim }}"
  with_items: "{{ postgresql_dbs.all }}"
  when: item.host in groups.citusdb_master
