---
# postgresql_ext bug https://github.com/ansible-collections/community.general/pull/1078
- name: Get available citus version
  become: yes
  become_user: postgres
  shell: psql postgres -q  -t -c "select version from pg_available_extension_versions where name = 'citus' and version >= '{{ citus_version }}' order by version desc limit 1;"
  register: citus_version_available

- name: Add Citus Extension on Coordinator Database
  become: yes
  become_user: postgres
  postgresql_ext:
    name: citus
    db: "{{ item.name }}"
    version: "{{ citus_version_available.stdout | default(citus_version) | trim }}"
  with_items: "{{ postgresql_dbs.all }}"
  when: item.host == inventory_hostname

- name: Add Workers Nodes to the Cordinator
  become: yes
  become_user: postgres
  shell: psql {{ item.0.name }} -c "SELECT * from master_add_node( '{{item.1|ipaddr}}' , 6432);"
  with_nested:
  - "{{ postgresql_dbs.all }}"
  - "{{ groups['citusdb_worker'] | difference(groups['pg_standby']) }}"
  when: item.0.host in groups.citusdb_master
