deploy_env: icds
env_monitoring_id: icds
users:
  - dimagi
slack_alerts_channel: alerts-icds
git_repositories:
  - name: icds
    url: git@github.com:dimagi/commcare-icds.git
    dest: icds
    deploy_key: deploy_key.pem
    is_private: true
deploy_keys:
  deploy_key.vault: deploy_key.pem
  deploy_key_airflow.vault: deploy_key_airflow.pem
