---
- name: Set host's audit directory as a fact
  set_fact:
    host_audit_directory: "{{ audit_path }}/{{ ansible_hostname }}"

- name: Add host folder to audit
  delegate_to: localhost
  become_user: "{{ control_user }}"
  file:
    path: "{{ host_audit_directory }}/"
    state: directory

- name: Check file permissions
  include_tasks: "file_permissions.yml"
  vars:
    audit_directory: "{{ host_audit_directory }}"

- name: Check disk usage
  include_tasks: "disk_usage.yml"
  vars:
    audit_directory: "{{ host_audit_directory }}"

- name: Check filesystem health
  include_tasks: "filesystem_health.yml"
  vars:
    audit_directory: "{{ host_audit_directory }}"
