- name: Clone source code
  git_setup_release:
    repo: "{{ commcarehq_repository }}"
    dest: "{{ code_source }}"
    version: "{{ code_version }}"
    reference: "{{ code_releases }}/git_mirrors"
    key_file: "{{ deploy_key | default(omit, true) }}"
    previous_release: "{{ code_home }}"
