---
- name: restart supervisor
  systemd: 
    name: supervisor
    state: restarted
    daemon_reload: yes 

- name: restart clickhouse-server
  systemd:
    name: clickhouse-server
    state: restarted
    daemon_reload: yes

- name: restart sentry
  supervisorctl: name={{ item }} state=restarted
  with_items:
    - sentry-worker
    - sentry-cron
    - sentry-web

- name: restart snuba
  supervisorctl: name={{ item }} state=restarted
  with_items:
    - snuba-api