# Note: Make sure to add queues with associated tasks to the solo_queues list in
# validate_app_processes_config(), in app_processes.py, so they don't share a process with another queue.
- set_fact:
    celery_bash_runner: "{{ service_home }}/{{ deploy_env }}_celery_bash_runner.sh"
    supervisor_celery_workers: "{{ service_home }}/{{ deploy_env }}_supervisor_celery_workers.conf"

- set_fact:
    celery_managed_files:
      - "{{celery_bash_runner}}"
      - "{{ supervisor_service_files.celery_flower.file_path }}"
      - "{{ supervisor_service_files.celery_beat.file_path }}"
      - "{{supervisor_celery_workers}}"

- name: Add celery_bash_runner files
  template:
    src: "../templates/celery_bash_runner.sh.j2"
    dest: "{{ item.file_name }}"
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
    mode: 0644
  with_items:
    - file_name: "{{ celery_bash_runner }}"

- name: define special celery services
  template:
    src: "{{ item.template }}"
    dest: "{{ item.file_path }}"
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
    mode: 0600
  when: item.should_exist
  with_items:
    - "{{ supervisor_service_files.celery_flower }}"
    - "{{ supervisor_service_files.celery_beat }}"

- name: define celery workers
  template:
    src: "../templates/supervisor_celery_workers.conf.j2"
    dest: "{{ supervisor_celery_workers }}"
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
    mode: 0644
  when: app_processes_config.celery_processes.get(inventory_hostname) is defined
  with_items:
    - env_vars:
        http_proxy: "{% if http_proxy_address is defined %}http://{{ http_proxy_address }}:{{ http_proxy_port }}{% endif %}"
        https_proxy: "{% if http_proxy_address is defined %}https://{{ http_proxy_address }}:{{ http_proxy_port }}{% endif %}"
        no_proxy: "{% if http_proxy_address is defined %}{{ groups['all'] | join(',') }},{{ app_processes_config.additional_no_proxy_hosts }}{% endif %}"
        PROMETHEUS_PUSHGATEWAY_HOST: "{% if prometheus_celery_pushgateway is defined %}{{ prometheus_celery_pushgateway }}{% endif %}"
        TMPDIR: '{{ encrypted_tmp }}'
