- name: Creates Prometheus Metrics directory
  become: yes
  file:
    path: "{{ metrics_home }}"
    state: directory
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
  tags: services

- name: define prometheus service
  become: yes
  template:
    src: "{{ supervisor_service_files.prometheus.template }}"
    dest: "{{ supervisor_service_files.prometheus.file_path }}"
    owner: "{{ cchq_user }}"
    group: "{{ cchq_user }}"
    mode: 0644
  when: supervisor_service_files.prometheus.should_exist
