# note: if we want a non-apt install we could change to use something like one of these:
# https://github.com/glynnbird/ansible-install-kafka/blob/master/tasks/install-zookeeper.yml
# https://github.com/rackerlabs/ansible-kafka/blob/master/playbooks/roles/zookeeper/tasks/main.yml
- name: install zookeeper
  become: yes
  apt:
    name:
      - zookeeper
      - zookeeperd

- name: configure server id
  template: src=myid.j2 dest="{{zookeeper_conf_dir}}/myid"
  tags: zoo_conf

- name: configure Zookeeper properties
  template: src=zoo.cfg.j2 dest="{{zookeeper_conf_dir}}/zoo.cfg"
  tags: zoo_conf

- name: restart zookeeper service
  service: name=zookeeper state=restarted
  tags: zoo_conf
