# Web address of your HQ instance (e.g. example.com)
site_host: "example.com"

# Ansible inventory name for this server (e.g. hqserver1).
#server_inventory_name: ""  Leave out for now

# Host address of this server. This is used to set server's email address (e.g. exampelserver1.example.com)
server_host_name: "exampelserver1.example.com"

# Your SSH public key string to enable passwordless auth to this server
# You can find this in your local machine's ~/.ssh/id_rsa.pub (not server)
ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDpDc9jdR2BS+GZy7iikNbWhW8R+7m0v2IIlKySl94qFAzSOt7yFmqntze/eiZsJ/zn0G95rRqd8zqFkvRaf3WY6paRKdejdI0tlj/p2zdRwB7aOSaUor3eSAdy2dt9pYAjnuU82mw5gCn4W94b8iyHbgd4S6YK6pXqTVzzt7llkvMPr9WtK2g/c8C00NopQZC5Nmff/MzVJQHCnvRyU/vChwW2CCXw6/OW3GLfe2CUD8w29CDS4Lo88qJrKeiZc8WOoHjuIwet0/gm4VS7+IiFDR9+9+XanZOycWmSfLnDPHPCAQHD9VJpaT7NmFU+YZa6cSiQ6nXEDIGov9jXWwLJA86H6MOYuDLFNfp8ymzdG2Jtl+6b7PBBJrhTruCmpglBJ23US6JE827zcnfO978MgINfjslpKAG1EsnOjANBLNPa6Bd4dyciQRgU7DdNge5MW2Ib83Gkgz5meD0ihmWM13B/gNNFcpTEdpa7+GDI26iVDQz+gj+5mW8LL69B+azENsrNeCGIemJ4j7rwTEt4Zx1lvlz0CusA+BZWCeZRiE36L+Ew5+ttWxG7Ayni/E1/RlQPQuOD0+PR5anjsrQ2PJqFoSjr/wlL98zZm4UfKFtILXYXQFZqd8VI9QITuMFvepAqSqlaVJi5TIOCks4xUi7q74dMYYxL1PswXqQ8rQ== csmit@dimagi.com"

# The username to use for your user to be created on the server. This will be tied to above public key
ssh_username: "charl"
env_name: cluster
deploy_branch: automated-cluster-setup-test
