# Web address of your HQ instance (e.g. example.com)
site_host: "cluster.test"

# Ansible inventory name for this server (e.g. hqserver1).
#server_inventory_name: ""  Leave out for now

# Host address of this server. This is used to set server's email address (e.g. exampelserver1.example.com)
server_host_name: "cluster"

# Your SSH public key string to enable passwordless auth to this server
# You can find this in your local machine's ~/.ssh/id_rsa.pub (not server)
ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCsvztyx7UNbbxR67UcwnAXDAEZezTfqTTMtEWdA/kVntDYs4X1E46rbJXcmPbMcCnZnOzqDHU+oLHuRM4i+03T9N/oazbJp5i6MK8sPoMZxn7ISItDxnBUaM01hrBdhzXQhGYqfMNGRlwMQ+gzwv0pdbVo3INRpId4CX50p6vY+XxTvElGaFKohaNvCnlYrD8S7V4W6vLLlOHL0zmt5djLvPoOy4IhSRUz5dU/EZXXsWje2oYo1qEHdBDoArxs1PfB/RB8aF9SpeEVCrHmdQu5wbYAkqE8vX+umBJh3GesNjF8Pq0+qzpCLf6VLBof5j9WcI1sDHZZTSbWl2Ib+xqylErn5DHn6PFC5bT+g3ycrOYJbIhhDh5ONtRYQ8FijUq3NJ5YXs3uvkteHkGVknJCQtjJjCTK9u1UTbOgXTdk04me8azcRajjA3reqkfnXx3bXPtUPiN3Z4sZlsUyOj7G4dR27mHf/uIgOqKqaDBWsim/MgJ9GqusM08n35QxZJyG7x44W2Y6bchJdawVTB9OLkOGSXnvvyaoWBw1HD7aaYiWUxOSg4oRtoomsFtGLuDpJzCwLcfmv8cKNBQiILcbgYeLTabJiPth4hsMNYLlYRQqiXzovg2WP9uzvJjTgiQ+nM+35K8LHgYHwF8vMKTYr1bfQ8kptUpO3pYe2/Ez3w== chris.smit@dimagi.com"

# The username to use for your user to be created on the server. This will be tied to above public key
ssh_username: "ubuntu" # default AWS user
env_name: cluster
deploy_branch: cs/automated-cluster-setup
