- name: Install custom checks
  get_url:
    url: "{{ item.url }}"
    dest: "/etc/datadog-agent/checks.d/{{ item.name }}.py"
    sha256sum: "{{ item.sha256sum }}"
    force: yes
  notify: restart datadog
  when: item.enabled
  loop: "{{ datadog_custom_integrations }}"
  tags:
    - datadog_integrations

- name: Add datadog integration configs
  template: src="{{ item.name }}.yaml.j2" dest="/etc/datadog-agent/conf.d/{{ item.name }}.d/conf.yaml" owner="dd-agent" group="dd-agent"
  notify: restart datadog
  when: item is defined and item.enabled
  with_items:
    - {"name": "elastic", "enabled": "{{ datadog_integration_elastic }}"}
    - {"name": "gunicorn", "enabled": "{{ datadog_integration_gunicorn }}"}
    - {"name": "kafka", "enabled": "{{ datadog_integration_kafka }}"}
    - {"name": "kafka_consumer", "enabled": "{{ datadog_integration_kafka_consumer }}"}
    - {"name": "nginx", "enabled": "{{ datadog_integration_nginx }}"}
    - {"name": "pgbouncer", "enabled": "{{ datadog_integration_pgbouncer }}"}
    - {"name": "postgres", "enabled": "{{ datadog_integration_postgres }}"}
    - {"name": "process", "enabled": "{{ datadog_integration_postgres_receiver }}"}
    - {"name": "rabbitmq", "enabled": "{{ datadog_integration_rabbitmq }}"}
    - {"name": "redisdb", "enabled": "{{ datadog_integration_redisdb }}"}
    - {"name": "zk", "enabled": "{{ datadog_integration_zk }}"}
    - {"name": "celery_custom", "enabled": "{{ app_processes_config.celery_processes.get(inventory_hostname).flower is defined }}"}
    - {"name": "couch", "enabled": "{{ inventory_hostname == couchdb2_first_host }}"}
    - {"name": "couch_custom", "enabled": "{{ inventory_hostname == couchdb2_first_host }}"}
    - {"name": "http_check", "enabled": "{{ datadog_integration_http and inventory_hostname == groups.proxy[0] }}"}
    - {"name": "haproxy", "enabled": "{{ datadog_integration_haproxy }}"}
    - {"name": "tcp_check", "enabled": "{{ datadog_integration_tcp_check }}"}
    - {"name": "disk", "enabled": "{{ datadog_integration_disk_check }}"}
  tags:
    - datadog_integrations
