- name: Remove old datadog apt key
  apt_key: id=382E94DE keyserver=keyserver.ubuntu.com state=absent

- name: Add datadog apt key
  apt_key: id=F14F620E keyserver=keyserver.ubuntu.com state=present

- name: Add datadog apt repo
  apt_repository: repo='deb http://apt.datadoghq.com/ stable main' state=present update_cache=yes

- name: Install datadog agent
  apt: name=datadog-agent state=latest update_cache=yes cache_valid_time=7200

- name: Copy datadog conf
  template:
    group: dd-agent
    owner: dd-agent
    src: datadog.conf.j2
    dest: /etc/dd-agent/datadog.conf
  notify: restart datadog

- name: Make sure datadog agent is started
  service: name=datadog-agent state=started
  tags:
    - after-reboot

- name: Pull java tracer
  become: true
  become_user: "{{ cchq_user }}"
  get_url:
    url: "https://dtdg.co/latest-java-tracer"
    dest: "{{ cchq_home }}/dd-java-agent.jar"
  when: "inventory_hostname in groups.formplayer"

- import_tasks: add_integrations.yml
  when: DATADOG_ENABLED
  tags:
    - datadog_integrations

- import_tasks: remove_integrations.yml
  tags:
    - datadog_integrations
