---
- name: Restart pgbouncer (classic)
  become: yes
## unfortunately -R (online restart) is not sufficient
## to make so_reuseport effective
# shell: su -c "/usr/sbin/pgbouncer -R -d /etc/pgbouncer/pgbouncer.ini" - postgres
  systemd:
    name: "pgbouncer"
    state: restarted

- name: Stop and disable pgbouncer (classic)
  become: yes
  systemd:
    name: "pgbouncer"
    state: stopped
    enabled: no
    masked: yes

- name: Reload systemd
  become: yes
  systemd:
    daemon_reload: yes

- name: Start and enable pgbouncer
  become: yes
  systemd:
    name: "pgbouncer-multiprocess@{{ item }}"
    state: started
    enabled: yes
    masked: no
  with_sequence: count={{ pgbouncer_processes | default(1) }}

- name: Restart pgbouncer
  become: yes
  systemd:
    name: "pgbouncer-multiprocess@{{ item }}"
    state: restarted
  with_sequence: count={{ pgbouncer_processes | default(1) }}

- name: Reload pgbouncer
  become: yes
  systemd:
    name: "pgbouncer-multiprocess@{{ item }}"
    state: reloaded
  with_sequence: count={{ pgbouncer_processes | default(1) }}

