---
- name: Stop default pgbouncer
  become: yes
  systemd:
    name: pgbouncer
    state: stopped
    enabled: no

- name: Reload systemd
  become: yes
  systemd:
    daemon_reload: yes

- name: Restart pgbouncer
  become: yes
  systemd:
    name: pgbouncer-multiprocess@{{ item }}
    enabled: yes
    masked: no
    state: restarted
  with_sequence: count={{ pgbouncer_processes | default(1) }}

