tag_deploy_commits: True
use_shared_dir_for_staticfiles: True
shared_dir_for_staticfiles: /mnt/shared/temp
deploy_event_url: https://api.github.com/repos/dimagi/dimagi-qa/dispatches
acceptable_maintenance_window:
  hour_start: 2
  hour_end: 4
  timezone: US/Eastern
