---
- name: Common Database Machine Setup
  hosts:
    - kafka
    - zookeeper
  become: true
  roles:
    - {role: ecryptfs, tags: 'ecryptfs'}

- name: Zookeeper
  hosts: zookeeper
  become: true
  roles:
    - {role: zookeeper, tags: 'zookeeper'}

- name: Kafka
  hosts: kafka
  become: true
  environment:
    JMX_PORT: 9999
  roles:
    - {role: kafka, tags: 'kafka'}

- name: Disable THP
  become: true
  hosts:
    - zookeeper
    - kafka
  tags:
    - kernel_tuning
    - after-reboot
  roles:
    - role: kernel_tune
 
- name: Kafka system logs rolling configurations
  hosts: kafka
  become: true
  roles:
    - role: ansible-logrotate
      logrotate_scripts:
        - name: "{{ deploy_env }}_kafka"
          paths:
            - "{{ kafka_log_dir }}/*.log.????-??-??-??"
            - "{{ kafka_log_dir }}/*.out.*"
          options:
            - daily
            - rotate 4
            - missingok
            - compress
            - nocreate
            - notifempty
