# NOTE this playbook can be used to deploy a new version of commcare-hq. The
# similarly named deploy_commcarehq.yml playbook is used to configure machines
# to run commcare-hq, and is expected to be run less frequently than this one.

- name: Deploy CommCare HQ
  hosts:
    - webworkers
    - celery
    - pillowtop
    - proxy
    - django_manage
  tasks:
    - name: Get code version
      include_role:
        name: deploy_hq
        tasks_from: get_code_version
      tags: private_release
      when: code_version is not defined

    - import_role: {name: deploy_hq}
      vars:
        if_not_done: setup_release_common
      tags: private_release

    - import_role: {name: deploy_hq}
      vars:
        if_not_done: setup_release

- name: Copy static JS
  hosts: proxy
  tasks:
    - include_role: {name: deploy_hq}
      vars:
        if_not_done: copy_release_files
        item: staticfiles/CACHE/js

- name: Install javascript dependencies
  hosts: [webworkers, celery, proxy]
  tasks:
    - import_role: {name: deploy_hq}
      vars:
        if_not_done: yarn_install

- name: Collect static files
  hosts: [webworkers, proxy]
  tasks:
    - import_role: {name: deploy_hq}
      vars:
        if_not_done: staticfiles_collect

- name: Compress static files
  hosts: proxy[0]
  tasks:
    - import_role: {name: deploy_hq}
      vars:
        if_not_done: staticfiles_compress

- name: Update translations
  hosts:
    - webworkers
    - celery
    - pillowtop
    - proxy
    - django_manage
  tasks:
    - import_role: {name: deploy_hq}
      vars:
        if_not_done: update_translations

- name: Run migrations
  hosts: webworkers[0]
  tasks:
    - import_role: {name: deploy_hq}
      vars:
        if_not_done: run_migrations

- name: Pull staticfiles manifest
  hosts: webworkers
  tasks:
    - import_role: {name: deploy_hq}
      vars:
        if_not_done: staticfiles_pull_manifest

- name: Pull staticfiles cache
  hosts: proxy[1:]
  tasks:
    - name: Assert single proxy host
      fail:
        msg: >-
          There should be only one 'proxy' host. Ensure that only one host is
          assigned to the 'proxy' group, or set 'shared_dir_for_staticfiles'.
      when: not shared_dir_for_staticfiles

    - import_role: {name: deploy_hq}
      vars:
        if_not_done: staticfiles_pull_cache
