---
- import_playbook: deploy_efs_mount_shared_dir.yml
  when:
    - efs_shared_mount_endpoint is defined
    - efs_shared_mount_dir is defined
    - efs_shared_mount_options is defined
- import_playbook: roles/shared_dir.yml
  when: 
    - efs_shared_mount_endpoint is not defined
    - efs_shared_mount_dir is not defined
    - efs_shared_mount_options is not defined
