---

- name: Formplayer EFS
  hosts: formplayer
  become: true
  roles:
    - role: aws-efs
      vars:
        efs_mount_dir: /opt/formplayer_data
        efs_mount_uid: "{{ cchq_uid|default(None) }}"
        efs_mount_gid: "{{ cchq_gid|default(None) }}"
      when: "formplayer_efs_dns|default(False)"
      tags:
        - efs

- name: Formplayer
  hosts: formplayer
  become: true
  roles:
    - role: formplayer
      vars:
        formplayer_data_dir: "{{ '/opt/formplayer_data' if use_formplayer_efs|default(False) else (encrypted_root + '/formplayer') }}"
      tags: formplayer
    - role: kinesis_agent
      tags: kinesis-agent
  handlers:
    - include: roles/monit/handlers/main.yml

- name: Cleanup formplayer releases
  hosts: formplayer
  tasks:
    - name: List of releases
      find:
        paths="{{ formplayer_build_dir }}"
        file_type=directory
      register: releases

    - name: Check for current release
      stat:
        path="{{ item.path }}"
      with_items: "{{ (releases.files | sort(attribute='ctime')) }}"
      register: stat_results

    - debug: msg="{{ item.lnk_source }}"
      with_items: "{{ stat_results }}"
      when: item.stat.exists == true

#    - name: Keep the last 2 releases
#      file:
#        path="{{ item.path }}"
#        state=absent
#      with_items:
#        - "{{ (releases.files | sort(attribute='ctime'))[:-2] }}"
