---
- name: Common Database Machine Setup
  hosts:
    - couchdb3
  become: true
  roles:
    - {role: ecryptfs, tags: 'ecryptfs'}
    - {role: backups, tags: 'backups'}

- name: Couchdb 3.0
  hosts: couchdb3
  become: true
  roles:
    - {role: couchdb3, tags: 'couchdb3'}

- name: Couchdb3 log rolling configurations
  hosts: couchdb3
  become: true
  roles:
    - role: ansible-logrotate
      tags:
        - couchdb3
        - logging
      logrotate_scripts:
        - name: "{{ deploy_env }}_couchdb3"
          path: "{{ couchdb_dir }}/var/log/*.stderr"
          options:
            - hourly
            - size 300M
            - rotate 100
            - missingok
            - compress
            - delaycompress
            - copytruncate
            - nocreate
            - notifempty

              
- name: Couchdb3 proxy
  hosts: couchdb3_proxy
  become: true
  tasks:
    - import_tasks: partials/couchdb3_proxy_nginx.yml
      when: not couchdb_use_haproxy
    - import_tasks: partials/couchdb3_proxy_haproxy.yml
      when: couchdb_use_haproxy|bool  
  tags: proxy 

- name: deploy keepalived
  hosts: couchdb3_proxy
  become: true
  vars:
     keepalived_check_process: "pgrep haproxy"
     keepalived_router_id: 52
  roles:
    - role: keepalived
      when: groups.couchdb3_proxy |length == 2
  tags: proxy
