---

- name: Formplayer EFS
  hosts: formplayer
  become: true
  roles:
    - role: aws-efs
      vars:
        efs_mount_dir: /opt/formplayer_data
        efs_mount_uid: "{{ cchq_uid|default(None) }}"
        efs_mount_gid: "{{ cchq_gid|default(None) }}"
      when: "formplayer_efs_dns|default(False)"
      tags:
        - efs

- name: Formplayer
  hosts: formplayer
  become: true
  roles:
    - role: formplayer
      vars:
        formplayer_data_dir: "{{ '/opt/formplayer_data' if use_formplayer_efs|default(False) else (encrypted_root + '/formplayer') }}"
      tags: formplayer
    - role: kinesis_agent
      tags: kinesis-agent
  handlers:
    - include: roles/monit/handlers/main.yml

- name: Cleanup formplayer releases
  hosts: formplayer
  tasks:
    - name: List of releases
      find:
        paths="{{ test_formplayer_build_dir }}"
        file_type=directory
      register: releases

    - name: Get stats on current release
      stat:
        path="{{ test_formplayer_current_dir }}"
      register: current_release

    - name: Delete all releases except the current and most recent 2 releases
      file:
        path="{{ item.path }}"
        state=absent
      with_items:
        - "{{ (releases.files | sort(attribute='ctime'))[:-2] }}"
      when: item.path != current_release.stat.lnk_target
