- name: Restart non-webworker services
  hosts:
    - celery
    - pillowtop
    - proxy
  become: true
  vars_files: [roles/deploy_hq/vars/main.yml]
  any_errors_fatal: true
  tasks:
    - name: Set in-progress flag
      command:
        cmd: ./manage.py deploy_in_progress
        chdir: '{{ code_home }}'
      run_once: true

    - name: Restart services
      command: supervisorctl {{ item }}
      register: stop_loop_hack
      when: >-
        inventory_hostname not in groups.webworkers
        and not stop_loop_hack.failed | default(False)
      loop:
        - stop all
        - reread
        - update
        - start all

- import_playbook: restart_webworker_services.yml
