- name: Update current
  hosts:
    - webworkers
    - celery
    - pillowtop
    - proxy
    - django_manage
  become: true
  become_user: '{{ cchq_user }}'
  tasks:
    # The "code_source" variable comes from the "deploy_hq" role, which
    # is imported below. Apparently variables from "static imports" are
    # available to all tasks in the play, not only to role tasks.
    - name: Check for valid release
      stat:
        path: '{{ code_source }}'
      register: result

    - name: Fail on missing release
      fail:
        msg: "Release not found: {{ code_source }}"
      when: not result.stat.exists

    - import_role:
        name: deploy_hq
        tasks_from: update_current
