---
- name: Copy compaction script
  become: yes
  copy:
    src: "compact_couchdb.sh"
    dest: "/usr/local/sbin/compact_couchdb.sh"
    group: couchdb
    owner: couchdb
    mode: 0744
  tags:
    - cron

- name: Create Daily Cron job (compact)
  become: yes
  cron:
    name: "Compact DB"
    job: "/usr/local/sbin/compact_couchdb.sh -H {{ groups.couchdb2_proxy[0] }} -P {{ couchdb2_proxy_port }} -u {{ COUCH_USERNAME }} -p {{ COUCH_PASSWORD }}"
    minute: 0
    hour: "{{ nadir_hour|default(0) }}"
    user: couchdb
    cron_file: compact_couch
  tags:
    - cron
