- name: Install Python packages
  become: yes
  apt:
    name:
      - python3-pip
      - python3-dev
      - python3-setuptools

- name: Update pip & setuptools
  become: yes
  pip:
    name:
      - pip
      - setuptools
    state: latest
    executable: pip3
